### ISSUE TITLE
Laravel 5.3 / Redis / Socket.IO / Laravel-Echo private channels

### ISSUE THREAD

**Issue by pdroge84** [laravel/echo#151]
Hi,

I've been trying all weekend to get this working but after pulling alot of hair out i've stopped trying and going to ask here.

I've got a laravel project running in which i wish to have Redis with socket.io and laravel-echo working.
I got this all working with public channels no problem at all. Now i wish to have it working with private channels aswell, here comes the fun part, I can't get it to work.

After googling alot I still can't seem to find THE solution to my problem. I'll try to explain what I've got so far:

laravel-echo-server.json
```json
{
	"authHost": "http://192.168.10.10",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "***",
			"key": "***"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": "192.168.10.10",
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": ""
}
```

BroadcastServiceProvider.php boot method
``` php
public function boot()
    {
        Broadcast::routes();

        Broadcast::channel('tenant_id.*', function ($user, $tenant_id) {
            return true;
        });
    }
```

My event
``` php
class ProgressUpdated implements ShouldBroadcast
{
    use SerializesModels;

    public $tenantId;
    public $data;

    public function __construct($tenant_id)
    {
        $this->tenantId = $tenant_id;

        $this->data = array(
            'power'=> '10'
        );
    }

    public function broadcastOn()
    {
        return ['tenant_id.' . $this->tenantId];
    }
}
```

In the blade head:
```html
<meta name="csrf-token" content="{{ csrf_token() }}">
```

In my Vue template (script part)
``` javascript 
import Echo from "laravel-echo";
```

and in it's ready
```javascript
window.Echo = new Echo({
                broadcaster: 'socket.io',
                host: 'http://192.168.10.10:6001'
            });
```

and inside an method that does an API call first to define what the tenant_id is:
``` javascript
var channelName = 'tenant_id.' + _this.integration.tenant_id;
                    window.Echo.private(channelName).listen('ProgressUpdated', (e) => {
                        console.log(e.data.power);
                    });
```

gulp runs fine, no issues there.

Whenever i got to the page to subscribe to the channel, laravel-echo-server returns the following messages:
[11:36:56 AM] - BOpvHckeCQxfph8QAAAC could not be authenticated to private-tenant_id.1
Client can not be authenticated, got HTTP status 500

Could anyone please help me.

Thanks in advance.
Kind regards,
Pim Dröge

**Comment by kohenkatz** [comment]
`laravel-echo-server` is telling you that your Laravel application returned a 500 error when it called `/broadcasting/auth`.

Have you checked the `storage/logs/laravel.log` file to see if it says what the 500 error was?

**Comment by pdroge84** [comment]
@kohenkatz 
This is the error log:
This is the error in the log:
[2017-09-25 11:36:56] testing.ERROR: Illuminate\Session\TokenMismatchException in /home/vagrant/Code/application/bootstrap/cache/compiled.php:3314 Stack trace: #0 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure)) #1 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #2 /home/vagrant/Code/application/bootstrap/cache/compiled.php(13749): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #3 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #4 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #5 /home/vagrant/Code/application/bootstrap/cache/compiled.php(12155): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #6 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #7 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #8 /home/vagrant/Code/application/bootstrap/cache/compiled.php(13495): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #9 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #10 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #11 /home/vagrant/Code/application/bootstrap/cache/compiled.php(13432): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #12 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure)) #13 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #14 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10054): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #15 /home/vagrant/Code/application/bootstrap/cache/compiled.php(8356): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #16 /home/vagrant/Code/application/bootstrap/cache/compiled.php(8347): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request)) #17 /home/vagrant/Code/application/bootstrap/cache/compiled.php(8338): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #18 /home/vagrant/Code/application/bootstrap/cache/compiled.php(2575): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #19 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request)) #20 /home/vagrant/Code/application/bootstrap/cache/compiled.php(3374): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #21 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10069): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)) #22 /home/vagrant/Code/application/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #23 /home/vagrant/Code/application/bootstrap/cache/compiled.php(10054): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #24 /home/vagrant/Code/application/bootstrap/cache/compiled.php(2519): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #25 /home/vagrant/Code/application/bootstrap/cache/compiled.php(2503): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #26 /home/vagrant/Code/application/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #27 {main}

**Comment by kohenkatz** [comment]
`TokenMismatchException` means that there is something wrong with the CSRF token, most likely that you aren't sending it. See https://github.com/tlaverdure/laravel-echo-server/issues/68 for others who have had the same issue.

**Comment by darrynten** [comment]
I've been facing a similar issue which I've managed to fix.

I [opened a PR upstream](https://github.com/laravel/framework/pull/22207) with my fix, hoping it'll get accepted.

Try the change out, maybe it will work for you.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
